### ISSUE TITLE
Slideshow looks wonky

### ISSUE THREAD

**Issue by adamsong** [robodogs435frc/2015-Website-Redesign#14]
The slideshow images are all different sizes. (Someone should add this to the slideshow milestone)

**Comment by gabsillis** [comment]
I haven't seen that, the images should fit to 100% with and height of the slideshow_container class

**Comment by gabsillis** [comment]
Possible issues may be a max/min set in the Javascript file that makes the slideshow

**Comment by gabsillis** [comment]
What monitor sizes / resolutions is this occurring on?

**Comment by adamsong** [comment]
Nevermind. It appears the problem was cause by lack of style sheets.
