### ISSUE TITLE
New Pages (Header bar 'problem')

### ISSUE THREAD

**Issue by czvni** [robodogs435frc/2015-Website-Redesign#4]
Just a reminder that every new page's header bar (the line underneath the top of the page) is blue -- I wasn't sure what color we wanted them so I left it alone for now.

**Comment by gabsillis** [comment]
the header bar color should match the icon this should happen automatically with the php script which takes a regex of the current url

**Comment by adamsong** [comment]
This is not a problem anymore. It appears to have been fixed.

**Comment by sweeneyb** [comment]
If this is fixed, please mark it as closed.
